// Generated by rstantools.  Do not edit by hand.

/*
    hbamr is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    hbamr is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with hbamr.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_FBAM_MINI_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'FBAM_MINI', line 23, column 2 to column 25)",
                                                      " (in 'FBAM_MINI', line 24, column 2 to column 24)",
                                                      " (in 'FBAM_MINI', line 25, column 2 to column 22)",
                                                      " (in 'FBAM_MINI', line 26, column 2 to column 26)",
                                                      " (in 'FBAM_MINI', line 27, column 2 to column 22)",
                                                      " (in 'FBAM_MINI', line 28, column 2 to column 41)",
                                                      " (in 'FBAM_MINI', line 31, column 2 to column 22)",
                                                      " (in 'FBAM_MINI', line 32, column 2 to column 22)",
                                                      " (in 'FBAM_MINI', line 33, column 2 to column 21)",
                                                      " (in 'FBAM_MINI', line 34, column 2 to column 24)",
                                                      " (in 'FBAM_MINI', line 35, column 2 to column 20)",
                                                      " (in 'FBAM_MINI', line 36, column 2 to column 25)",
                                                      " (in 'FBAM_MINI', line 37, column 2 to column 25)",
                                                      " (in 'FBAM_MINI', line 38, column 2 to column 45)",
                                                      " (in 'FBAM_MINI', line 39, column 2 to column 45)",
                                                      " (in 'FBAM_MINI', line 40, column 2 to column 47)",
                                                      " (in 'FBAM_MINI', line 41, column 2 to column 48)",
                                                      " (in 'FBAM_MINI', line 43, column 4 to line 45, column 83)",
                                                      " (in 'FBAM_MINI', line 42, column 21 to line 46, column 3)",
                                                      " (in 'FBAM_MINI', line 42, column 2 to line 46, column 3)",
                                                      " (in 'FBAM_MINI', line 63, column 2 to column 18)",
                                                      " (in 'FBAM_MINI', line 64, column 2 to column 16)",
                                                      " (in 'FBAM_MINI', line 68, column 4 to column 37)",
                                                      " (in 'FBAM_MINI', line 66, column 4 to column 45)",
                                                      " (in 'FBAM_MINI', line 65, column 2 to line 68, column 37)",
                                                      " (in 'FBAM_MINI', line 69, column 2 to column 74)",
                                                      " (in 'FBAM_MINI', line 70, column 2 to column 71)",
                                                      " (in 'FBAM_MINI', line 74, column 4 to column 30)",
                                                      " (in 'FBAM_MINI', line 72, column 4 to column 77)",
                                                      " (in 'FBAM_MINI', line 71, column 2 to line 74, column 30)",
                                                      " (in 'FBAM_MINI', line 49, column 2 to column 27)",
                                                      " (in 'FBAM_MINI', line 50, column 2 to column 26)",
                                                      " (in 'FBAM_MINI', line 51, column 2 to column 32)",
                                                      " (in 'FBAM_MINI', line 52, column 2 to column 32)",
                                                      " (in 'FBAM_MINI', line 53, column 2 to column 31)",
                                                      " (in 'FBAM_MINI', line 54, column 2 to column 31)",
                                                      " (in 'FBAM_MINI', line 55, column 2 to column 33)",
                                                      " (in 'FBAM_MINI', line 56, column 2 to column 22)",
                                                      " (in 'FBAM_MINI', line 60, column 4 to column 42)",
                                                      " (in 'FBAM_MINI', line 58, column 4 to column 27)",
                                                      " (in 'FBAM_MINI', line 57, column 2 to line 60, column 42)",
                                                      " (in 'FBAM_MINI', line 2, column 2 to column 19)",
                                                      " (in 'FBAM_MINI', line 3, column 2 to column 19)",
                                                      " (in 'FBAM_MINI', line 4, column 2 to column 23)",
                                                      " (in 'FBAM_MINI', line 5, column 8 to column 13)",
                                                      " (in 'FBAM_MINI', line 5, column 2 to column 33)",
                                                      " (in 'FBAM_MINI', line 6, column 8 to column 13)",
                                                      " (in 'FBAM_MINI', line 6, column 2 to column 33)",
                                                      " (in 'FBAM_MINI', line 7, column 2 to column 19)",
                                                      " (in 'FBAM_MINI', line 8, column 2 to column 30)",
                                                      " (in 'FBAM_MINI', line 9, column 2 to column 30)",
                                                      " (in 'FBAM_MINI', line 10, column 8 to column 13)",
                                                      " (in 'FBAM_MINI', line 10, column 2 to column 44)",
                                                      " (in 'FBAM_MINI', line 11, column 32 to column 33)",
                                                      " (in 'FBAM_MINI', line 11, column 2 to column 37)",
                                                      " (in 'FBAM_MINI', line 12, column 2 to column 31)",
                                                      " (in 'FBAM_MINI', line 13, column 31 to column 36)",
                                                      " (in 'FBAM_MINI', line 13, column 2 to column 46)",
                                                      " (in 'FBAM_MINI', line 14, column 2 to column 30)",
                                                      " (in 'FBAM_MINI', line 15, column 2 to column 29)",
                                                      " (in 'FBAM_MINI', line 16, column 2 to column 33)",
                                                      " (in 'FBAM_MINI', line 19, column 2 to column 55)",
                                                      " (in 'FBAM_MINI', line 20, column 31 to column 36)",
                                                      " (in 'FBAM_MINI', line 20, column 2 to column 64)",
                                                      " (in 'FBAM_MINI', line 23, column 9 to column 10)",
                                                      " (in 'FBAM_MINI', line 24, column 9 to column 10)",
                                                      " (in 'FBAM_MINI', line 26, column 8 to column 9)",
                                                      " (in 'FBAM_MINI', line 28, column 31 to column 32)",
                                                      " (in 'FBAM_MINI', line 31, column 8 to column 9)",
                                                      " (in 'FBAM_MINI', line 32, column 9 to column 10)",
                                                      " (in 'FBAM_MINI', line 33, column 9 to column 10)",
                                                      " (in 'FBAM_MINI', line 34, column 9 to column 14)",
                                                      " (in 'FBAM_MINI', line 63, column 9 to column 10)",
                                                      " (in 'FBAM_MINI', line 64, column 9 to column 10)",
                                                      " (in 'FBAM_MINI', line 69, column 9 to column 10)",
                                                      " (in 'FBAM_MINI', line 70, column 9 to column 10)"};
#include <stan_meta_header.hpp>
class model_FBAM_MINI final : public model_base_crtp<model_FBAM_MINI> {
private:
  int N;
  int J;
  int N_obs;
  std::vector<int> ii;
  std::vector<int> jj;
  int B;
  int L;
  int R;
  std::vector<int> Y;
  Eigen::Matrix<double, -1, 1> V;
  int CV;
  Eigen::Matrix<double, -1, 1> holdout;
  double sigma_alpha;
  double sigma_beta;
  int MCMC;
  double tau_prior_rate;
  Eigen::Matrix<double, -1, 1> not_holdout;
 
public:
  ~model_FBAM_MINI() { }
  
  inline std::string model_name() const final { return "model_FBAM_MINI"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_FBAM_MINI(stan::io::var_context& context__,
                  unsigned int random_seed__ = 0,
                  std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_FBAM_MINI_namespace::model_FBAM_MINI";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 42;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 42;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 42;
      current_statement__ = 42;
      check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 43;
      context__.validate_dims("data initialization","J","int",
          context__.to_vec());
      J = std::numeric_limits<int>::min();
      
      current_statement__ = 43;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 43;
      current_statement__ = 43;
      check_greater_or_equal(function__, "J", J, 1);
      current_statement__ = 44;
      context__.validate_dims("data initialization","N_obs","int",
          context__.to_vec());
      N_obs = std::numeric_limits<int>::min();
      
      current_statement__ = 44;
      N_obs = context__.vals_i("N_obs")[(1 - 1)];
      current_statement__ = 44;
      current_statement__ = 44;
      check_greater_or_equal(function__, "N_obs", N_obs, 1);
      current_statement__ = 45;
      validate_non_negative_index("ii", "N_obs", N_obs);
      current_statement__ = 46;
      context__.validate_dims("data initialization","ii","int",
          context__.to_vec(N_obs));
      ii = std::vector<int>(N_obs, std::numeric_limits<int>::min());
      
      current_statement__ = 46;
      assign(ii, nil_index_list(), context__.vals_i("ii"),
        "assigning variable ii");
      current_statement__ = 46;
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        current_statement__ = 46;
        current_statement__ = 46;
        check_greater_or_equal(function__, "ii[sym1__]", ii[(sym1__ - 1)], 1);
      }
      current_statement__ = 47;
      validate_non_negative_index("jj", "N_obs", N_obs);
      current_statement__ = 48;
      context__.validate_dims("data initialization","jj","int",
          context__.to_vec(N_obs));
      jj = std::vector<int>(N_obs, std::numeric_limits<int>::min());
      
      current_statement__ = 48;
      assign(jj, nil_index_list(), context__.vals_i("jj"),
        "assigning variable jj");
      current_statement__ = 48;
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        current_statement__ = 48;
        current_statement__ = 48;
        check_greater_or_equal(function__, "jj[sym1__]", jj[(sym1__ - 1)], 1);
      }
      current_statement__ = 49;
      context__.validate_dims("data initialization","B","int",
          context__.to_vec());
      B = std::numeric_limits<int>::min();
      
      current_statement__ = 49;
      B = context__.vals_i("B")[(1 - 1)];
      current_statement__ = 49;
      current_statement__ = 49;
      check_greater_or_equal(function__, "B", B, 1);
      current_statement__ = 50;
      context__.validate_dims("data initialization","L","int",
          context__.to_vec());
      L = std::numeric_limits<int>::min();
      
      current_statement__ = 50;
      L = context__.vals_i("L")[(1 - 1)];
      current_statement__ = 50;
      current_statement__ = 50;
      check_greater_or_equal(function__, "L", L, 1);
      current_statement__ = 50;
      current_statement__ = 50;
      check_less_or_equal(function__, "L", L, J);
      current_statement__ = 51;
      context__.validate_dims("data initialization","R","int",
          context__.to_vec());
      R = std::numeric_limits<int>::min();
      
      current_statement__ = 51;
      R = context__.vals_i("R")[(1 - 1)];
      current_statement__ = 51;
      current_statement__ = 51;
      check_greater_or_equal(function__, "R", R, 1);
      current_statement__ = 51;
      current_statement__ = 51;
      check_less_or_equal(function__, "R", R, J);
      current_statement__ = 52;
      validate_non_negative_index("Y", "N_obs", N_obs);
      current_statement__ = 53;
      context__.validate_dims("data initialization","Y","int",
          context__.to_vec(N_obs));
      Y = std::vector<int>(N_obs, std::numeric_limits<int>::min());
      
      current_statement__ = 53;
      assign(Y, nil_index_list(), context__.vals_i("Y"),
        "assigning variable Y");
      current_statement__ = 53;
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        current_statement__ = 53;
        current_statement__ = 53;
        check_greater_or_equal(function__, "Y[sym1__]", Y[(sym1__ - 1)], -B);
      }
      current_statement__ = 53;
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        current_statement__ = 53;
        current_statement__ = 53;
        check_less_or_equal(function__, "Y[sym1__]", Y[(sym1__ - 1)], B);}
      current_statement__ = 54;
      validate_non_negative_index("V", "N", N);
      current_statement__ = 55;
      context__.validate_dims("data initialization","V","double",
          context__.to_vec(N));
      V = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(V, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> V_flat__;
        current_statement__ = 55;
        assign(V_flat__, nil_index_list(), context__.vals_r("V"),
          "assigning variable V_flat__");
        current_statement__ = 55;
        pos__ = 1;
        current_statement__ = 55;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 55;
          assign(V, cons_list(index_uni(sym1__), nil_index_list()),
            V_flat__[(pos__ - 1)], "assigning variable V");
          current_statement__ = 55;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 55;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 55;
        current_statement__ = 55;
        check_greater_or_equal(function__, "V[sym1__]", V[(sym1__ - 1)], -B);
      }
      current_statement__ = 55;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 55;
        current_statement__ = 55;
        check_less_or_equal(function__, "V[sym1__]", V[(sym1__ - 1)], B);}
      current_statement__ = 56;
      context__.validate_dims("data initialization","CV","int",
          context__.to_vec());
      CV = std::numeric_limits<int>::min();
      
      current_statement__ = 56;
      CV = context__.vals_i("CV")[(1 - 1)];
      current_statement__ = 56;
      current_statement__ = 56;
      check_greater_or_equal(function__, "CV", CV, 0);
      current_statement__ = 56;
      current_statement__ = 56;
      check_less_or_equal(function__, "CV", CV, 1);
      current_statement__ = 57;
      validate_non_negative_index("holdout", "N_obs", N_obs);
      current_statement__ = 58;
      context__.validate_dims("data initialization","holdout","double",
          context__.to_vec(N_obs));
      holdout = Eigen::Matrix<double, -1, 1>(N_obs);
      stan::math::fill(holdout, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> holdout_flat__;
        current_statement__ = 58;
        assign(holdout_flat__, nil_index_list(), context__.vals_r("holdout"),
          "assigning variable holdout_flat__");
        current_statement__ = 58;
        pos__ = 1;
        current_statement__ = 58;
        for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
          current_statement__ = 58;
          assign(holdout, cons_list(index_uni(sym1__), nil_index_list()),
            holdout_flat__[(pos__ - 1)], "assigning variable holdout");
          current_statement__ = 58;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 58;
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        current_statement__ = 58;
        current_statement__ = 58;
        check_greater_or_equal(function__, "holdout[sym1__]",
                               holdout[(sym1__ - 1)], 0);}
      current_statement__ = 58;
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        current_statement__ = 58;
        current_statement__ = 58;
        check_less_or_equal(function__, "holdout[sym1__]",
                            holdout[(sym1__ - 1)], 1);}
      current_statement__ = 59;
      context__.validate_dims("data initialization","sigma_alpha","double",
          context__.to_vec());
      sigma_alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 59;
      sigma_alpha = context__.vals_r("sigma_alpha")[(1 - 1)];
      current_statement__ = 59;
      current_statement__ = 59;
      check_greater_or_equal(function__, "sigma_alpha", sigma_alpha, 0);
      current_statement__ = 60;
      context__.validate_dims("data initialization","sigma_beta","double",
          context__.to_vec());
      sigma_beta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 60;
      sigma_beta = context__.vals_r("sigma_beta")[(1 - 1)];
      current_statement__ = 60;
      current_statement__ = 60;
      check_greater_or_equal(function__, "sigma_beta", sigma_beta, 0);
      current_statement__ = 61;
      context__.validate_dims("data initialization","MCMC","int",
          context__.to_vec());
      MCMC = std::numeric_limits<int>::min();
      
      current_statement__ = 61;
      MCMC = context__.vals_i("MCMC")[(1 - 1)];
      current_statement__ = 61;
      current_statement__ = 61;
      check_greater_or_equal(function__, "MCMC", MCMC, 0);
      current_statement__ = 61;
      current_statement__ = 61;
      check_less_or_equal(function__, "MCMC", MCMC, 1);
      current_statement__ = 62;
      tau_prior_rate = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 62;
      tau_prior_rate = ((2 - 1) / (B / 5.0));
      current_statement__ = 63;
      validate_non_negative_index("not_holdout", "N_obs", N_obs);
      current_statement__ = 64;
      not_holdout = Eigen::Matrix<double, -1, 1>(N_obs);
      stan::math::fill(not_holdout, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 64;
      assign(not_holdout, nil_index_list(), subtract(1, holdout),
        "assigning variable not_holdout");
      current_statement__ = 62;
      current_statement__ = 62;
      check_greater_or_equal(function__, "tau_prior_rate", tau_prior_rate, 0);
      current_statement__ = 64;
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        current_statement__ = 64;
        current_statement__ = 64;
        check_greater_or_equal(function__, "not_holdout[sym1__]",
                               not_holdout[(sym1__ - 1)], 0);}
      current_statement__ = 64;
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        current_statement__ = 64;
        current_statement__ = 64;
        check_less_or_equal(function__, "not_holdout[sym1__]",
                            not_holdout[(sym1__ - 1)], 1);}
      current_statement__ = 65;
      validate_non_negative_index("alpha_raw", "N", N);
      current_statement__ = 66;
      validate_non_negative_index("beta_raw", "N", N);
      current_statement__ = 67;
      validate_non_negative_index("theta_raw", "J", J);
      current_statement__ = 68;
      validate_non_negative_index("lambda", "N", N);
      current_statement__ = 69;
      validate_non_negative_index("theta", "J", J);
      current_statement__ = 70;
      validate_non_negative_index("alpha0", "N", N);
      current_statement__ = 71;
      validate_non_negative_index("beta0", "N", N);
      current_statement__ = 72;
      validate_non_negative_index("log_lik", "N_obs", N_obs);
      current_statement__ = 73;
      validate_non_negative_index("kappa", "N", N);
      current_statement__ = 74;
      validate_non_negative_index("chi", "N", N);
      current_statement__ = 75;
      validate_non_negative_index("alpha", "N", N);
      current_statement__ = 76;
      validate_non_negative_index("beta", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += N * 2;
      num_params_r__ += N * 2;
      num_params_r__ += 2;
      num_params_r__ += J;
      num_params_r__ += 1;
      num_params_r__ += N;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_FBAM_MINI_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, -1> alpha_raw;
      alpha_raw = Eigen::Matrix<local_scalar_t__, -1, -1>(N, 2);
      stan::math::fill(alpha_raw, DUMMY_VAR__);
      
      current_statement__ = 1;
      alpha_raw = in__.matrix(N, 2);
      Eigen::Matrix<local_scalar_t__, -1, -1> beta_raw;
      beta_raw = Eigen::Matrix<local_scalar_t__, -1, -1>(N, 2);
      stan::math::fill(beta_raw, DUMMY_VAR__);
      
      current_statement__ = 2;
      beta_raw = in__.matrix(N, 2);
      Eigen::Matrix<local_scalar_t__, -1, 1> theta_lr;
      theta_lr = Eigen::Matrix<local_scalar_t__, -1, 1>(2);
      stan::math::fill(theta_lr, DUMMY_VAR__);
      
      current_statement__ = 3;
      theta_lr = in__.vector(2);
      current_statement__ = 3;
      if (jacobian__) {
        current_statement__ = 3;
        assign(theta_lr, nil_index_list(),
          stan::math::ordered_constrain(theta_lr, lp__),
          "assigning variable theta_lr");
      } else {
        current_statement__ = 3;
        assign(theta_lr, nil_index_list(),
          stan::math::ordered_constrain(theta_lr),
          "assigning variable theta_lr");
      }
      std::vector<local_scalar_t__> theta_raw;
      theta_raw = std::vector<local_scalar_t__>(J, DUMMY_VAR__);
      
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        current_statement__ = 4;
        assign(theta_raw, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable theta_raw");}
      local_scalar_t__ tau;
      tau = DUMMY_VAR__;
      
      current_statement__ = 5;
      tau = in__.scalar();
      current_statement__ = 5;
      if (jacobian__) {
        current_statement__ = 5;
        tau = stan::math::lb_constrain(tau, 0, lp__);
      } else {
        current_statement__ = 5;
        tau = stan::math::lb_constrain(tau, 0);
      }
      Eigen::Matrix<local_scalar_t__, -1, 1> lambda;
      lambda = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
      stan::math::fill(lambda, DUMMY_VAR__);
      
      current_statement__ = 6;
      lambda = in__.vector(N);
      current_statement__ = 6;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 6;
        if (jacobian__) {
          current_statement__ = 6;
          assign(lambda, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lub_constrain(lambda[(sym1__ - 1)], 0, 1, lp__),
            "assigning variable lambda");
        } else {
          current_statement__ = 6;
          assign(lambda, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lub_constrain(lambda[(sym1__ - 1)], 0, 1),
            "assigning variable lambda");
        }}
      std::vector<local_scalar_t__> theta;
      theta = std::vector<local_scalar_t__>(J, DUMMY_VAR__);
      
      Eigen::Matrix<local_scalar_t__, -1, -1> alpha0;
      alpha0 = Eigen::Matrix<local_scalar_t__, -1, -1>(N, 2);
      stan::math::fill(alpha0, DUMMY_VAR__);
      
      Eigen::Matrix<local_scalar_t__, -1, -1> beta0;
      beta0 = Eigen::Matrix<local_scalar_t__, -1, -1>(N, 2);
      stan::math::fill(beta0, DUMMY_VAR__);
      
      Eigen::Matrix<local_scalar_t__, -1, 1> log_lik;
      log_lik = Eigen::Matrix<local_scalar_t__, -1, 1>(N_obs);
      stan::math::fill(log_lik, DUMMY_VAR__);
      
      current_statement__ = 11;
      assign(theta, nil_index_list(), theta_raw, "assigning variable theta");
      current_statement__ = 12;
      assign(theta, cons_list(index_uni(L), nil_index_list()),
        theta_lr[(1 - 1)], "assigning variable theta");
      current_statement__ = 13;
      assign(theta, cons_list(index_uni(R), nil_index_list()),
        theta_lr[(2 - 1)], "assigning variable theta");
      current_statement__ = 14;
      assign(alpha0,
        cons_list(index_omni(), cons_list(index_uni(1), nil_index_list())),
        multiply(
          rvalue(alpha_raw,
            cons_list(index_omni(),
              cons_list(index_uni(1), nil_index_list())), "alpha_raw"),
          sigma_alpha), "assigning variable alpha0");
      current_statement__ = 15;
      assign(alpha0,
        cons_list(index_omni(), cons_list(index_uni(2), nil_index_list())),
        multiply(
          rvalue(alpha_raw,
            cons_list(index_omni(),
              cons_list(index_uni(2), nil_index_list())), "alpha_raw"),
          sigma_alpha), "assigning variable alpha0");
      current_statement__ = 16;
      assign(beta0,
        cons_list(index_omni(), cons_list(index_uni(1), nil_index_list())),
        stan::math::exp(
          multiply(
            rvalue(beta_raw,
              cons_list(index_omni(),
                cons_list(index_uni(1), nil_index_list())), "beta_raw"),
            sigma_beta)), "assigning variable beta0");
      current_statement__ = 17;
      assign(beta0,
        cons_list(index_omni(), cons_list(index_uni(2), nil_index_list())),
        minus(
          stan::math::exp(
            multiply(
              rvalue(beta_raw,
                cons_list(index_omni(),
                  cons_list(index_uni(2), nil_index_list())), "beta_raw"),
              sigma_beta))), "assigning variable beta0");
      current_statement__ = 20;
      for (int n = 1; n <= N_obs; ++n) {
        current_statement__ = 18;
        assign(log_lik, cons_list(index_uni(n), nil_index_list()),
          log_mix(lambda[(ii[(n - 1)] - 1)],
            normal_lpdf<false>(Y[(n - 1)],
              (rvalue(alpha0,
                 cons_list(index_uni(ii[(n - 1)]),
                   cons_list(index_uni(1), nil_index_list())), "alpha0") +
                (rvalue(beta0,
                   cons_list(index_uni(ii[(n - 1)]),
                     cons_list(index_uni(1), nil_index_list())), "beta0") *
                  theta[(jj[(n - 1)] - 1)])), tau),
            normal_lpdf<false>(Y[(n - 1)],
              (rvalue(alpha0,
                 cons_list(index_uni(ii[(n - 1)]),
                   cons_list(index_uni(2), nil_index_list())), "alpha0") +
                (rvalue(beta0,
                   cons_list(index_uni(ii[(n - 1)]),
                     cons_list(index_uni(2), nil_index_list())), "beta0") *
                  theta[(jj[(n - 1)] - 1)])), tau)),
          "assigning variable log_lik");}
      {
        current_statement__ = 31;
        lp_accum__.add(normal_lpdf<propto__>(theta_raw, 0, B));
        current_statement__ = 32;
        lp_accum__.add(normal_lpdf<propto__>(theta_lr, 0, B));
        current_statement__ = 33;
        lp_accum__.add(
          normal_lpdf<propto__>(
            rvalue(alpha_raw,
              cons_list(index_omni(),
                cons_list(index_uni(1), nil_index_list())), "alpha_raw"), 0,
            1));
        current_statement__ = 34;
        lp_accum__.add(
          normal_lpdf<propto__>(
            rvalue(alpha_raw,
              cons_list(index_omni(),
                cons_list(index_uni(2), nil_index_list())), "alpha_raw"), 0,
            1));
        current_statement__ = 35;
        lp_accum__.add(
          normal_lpdf<propto__>(
            rvalue(beta_raw,
              cons_list(index_omni(),
                cons_list(index_uni(1), nil_index_list())), "beta_raw"), 0,
            1));
        current_statement__ = 36;
        lp_accum__.add(
          normal_lpdf<propto__>(
            rvalue(beta_raw,
              cons_list(index_omni(),
                cons_list(index_uni(2), nil_index_list())), "beta_raw"), 0,
            1));
        current_statement__ = 37;
        lp_accum__.add(gamma_lpdf<propto__>(tau, 2, tau_prior_rate));
        current_statement__ = 38;
        lp_accum__.add(beta_lpdf<propto__>(lambda, 2, 1));
        current_statement__ = 41;
        if (logical_eq(CV, 0)) {
          current_statement__ = 40;
          lp_accum__.add(sum(log_lik));
        } else {
          current_statement__ = 39;
          lp_accum__.add(sum(elt_multiply(log_lik, not_holdout)));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_FBAM_MINI_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, -1> alpha_raw;
      alpha_raw = Eigen::Matrix<double, -1, -1>(N, 2);
      stan::math::fill(alpha_raw, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      alpha_raw = in__.matrix(N, 2);
      Eigen::Matrix<double, -1, -1> beta_raw;
      beta_raw = Eigen::Matrix<double, -1, -1>(N, 2);
      stan::math::fill(beta_raw, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      beta_raw = in__.matrix(N, 2);
      Eigen::Matrix<double, -1, 1> theta_lr;
      theta_lr = Eigen::Matrix<double, -1, 1>(2);
      stan::math::fill(theta_lr, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      theta_lr = in__.vector(2);
      current_statement__ = 3;
      assign(theta_lr, nil_index_list(),
        stan::math::ordered_constrain(theta_lr),
        "assigning variable theta_lr");
      std::vector<double> theta_raw;
      theta_raw = std::vector<double>(J, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        current_statement__ = 4;
        assign(theta_raw, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable theta_raw");}
      double tau;
      tau = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      tau = in__.scalar();
      current_statement__ = 5;
      tau = stan::math::lb_constrain(tau, 0);
      Eigen::Matrix<double, -1, 1> lambda;
      lambda = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(lambda, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 6;
      lambda = in__.vector(N);
      current_statement__ = 6;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 6;
        assign(lambda, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lub_constrain(lambda[(sym1__ - 1)], 0, 1),
          "assigning variable lambda");}
      std::vector<double> theta;
      theta = std::vector<double>(J, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, -1> alpha0;
      alpha0 = Eigen::Matrix<double, -1, -1>(N, 2);
      stan::math::fill(alpha0, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, -1> beta0;
      beta0 = Eigen::Matrix<double, -1, -1>(N, 2);
      stan::math::fill(beta0, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> log_lik;
      log_lik = Eigen::Matrix<double, -1, 1>(N_obs);
      stan::math::fill(log_lik, std::numeric_limits<double>::quiet_NaN());
      
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          vars__.emplace_back(
            rvalue(alpha_raw,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "alpha_raw"));
        }}
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          vars__.emplace_back(
            rvalue(beta_raw,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "beta_raw"));
        }}
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        vars__.emplace_back(theta_lr[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        vars__.emplace_back(theta_raw[(sym1__ - 1)]);}
      vars__.emplace_back(tau);
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(lambda[(sym1__ - 1)]);}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 11;
      assign(theta, nil_index_list(), theta_raw, "assigning variable theta");
      current_statement__ = 12;
      assign(theta, cons_list(index_uni(L), nil_index_list()),
        theta_lr[(1 - 1)], "assigning variable theta");
      current_statement__ = 13;
      assign(theta, cons_list(index_uni(R), nil_index_list()),
        theta_lr[(2 - 1)], "assigning variable theta");
      current_statement__ = 14;
      assign(alpha0,
        cons_list(index_omni(), cons_list(index_uni(1), nil_index_list())),
        multiply(
          rvalue(alpha_raw,
            cons_list(index_omni(),
              cons_list(index_uni(1), nil_index_list())), "alpha_raw"),
          sigma_alpha), "assigning variable alpha0");
      current_statement__ = 15;
      assign(alpha0,
        cons_list(index_omni(), cons_list(index_uni(2), nil_index_list())),
        multiply(
          rvalue(alpha_raw,
            cons_list(index_omni(),
              cons_list(index_uni(2), nil_index_list())), "alpha_raw"),
          sigma_alpha), "assigning variable alpha0");
      current_statement__ = 16;
      assign(beta0,
        cons_list(index_omni(), cons_list(index_uni(1), nil_index_list())),
        stan::math::exp(
          multiply(
            rvalue(beta_raw,
              cons_list(index_omni(),
                cons_list(index_uni(1), nil_index_list())), "beta_raw"),
            sigma_beta)), "assigning variable beta0");
      current_statement__ = 17;
      assign(beta0,
        cons_list(index_omni(), cons_list(index_uni(2), nil_index_list())),
        minus(
          stan::math::exp(
            multiply(
              rvalue(beta_raw,
                cons_list(index_omni(),
                  cons_list(index_uni(2), nil_index_list())), "beta_raw"),
              sigma_beta))), "assigning variable beta0");
      current_statement__ = 20;
      for (int n = 1; n <= N_obs; ++n) {
        current_statement__ = 18;
        assign(log_lik, cons_list(index_uni(n), nil_index_list()),
          log_mix(lambda[(ii[(n - 1)] - 1)],
            normal_lpdf<false>(Y[(n - 1)],
              (rvalue(alpha0,
                 cons_list(index_uni(ii[(n - 1)]),
                   cons_list(index_uni(1), nil_index_list())), "alpha0") +
                (rvalue(beta0,
                   cons_list(index_uni(ii[(n - 1)]),
                     cons_list(index_uni(1), nil_index_list())), "beta0") *
                  theta[(jj[(n - 1)] - 1)])), tau),
            normal_lpdf<false>(Y[(n - 1)],
              (rvalue(alpha0,
                 cons_list(index_uni(ii[(n - 1)]),
                   cons_list(index_uni(2), nil_index_list())), "alpha0") +
                (rvalue(beta0,
                   cons_list(index_uni(ii[(n - 1)]),
                     cons_list(index_uni(2), nil_index_list())), "beta0") *
                  theta[(jj[(n - 1)] - 1)])), tau)),
          "assigning variable log_lik");}
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          vars__.emplace_back(theta[(sym1__ - 1)]);}
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            vars__.emplace_back(
              rvalue(alpha0,
                cons_list(index_uni(sym2__),
                  cons_list(index_uni(sym1__), nil_index_list())), "alpha0"));
          }}
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            vars__.emplace_back(
              rvalue(beta0,
                cons_list(index_uni(sym2__),
                  cons_list(index_uni(sym1__), nil_index_list())), "beta0"));
          }}
        for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
          vars__.emplace_back(log_lik[(sym1__ - 1)]);}
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> kappa;
      kappa = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(kappa, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> chi;
      chi = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(chi, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 25;
      if (logical_eq(MCMC, 1)) {
        current_statement__ = 24;
        assign(kappa, nil_index_list(),
          to_vector(bernoulli_rng(lambda, base_rng__)),
          "assigning variable kappa");
      } else {
        current_statement__ = 23;
        assign(kappa, nil_index_list(), to_vector(stan::math::round(lambda)),
          "assigning variable kappa");
      }
      Eigen::Matrix<double, -1, 1> alpha;
      alpha = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(alpha, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 26;
      assign(alpha, nil_index_list(),
        add(
          elt_multiply(kappa,
            rvalue(alpha0,
              cons_list(index_omni(),
                cons_list(index_uni(1), nil_index_list())), "alpha0")),
          elt_multiply(subtract(1, kappa),
            rvalue(alpha0,
              cons_list(index_omni(),
                cons_list(index_uni(2), nil_index_list())), "alpha0"))),
        "assigning variable alpha");
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 27;
      assign(beta, nil_index_list(),
        add(
          elt_multiply(kappa,
            rvalue(beta0,
              cons_list(index_omni(),
                cons_list(index_uni(1), nil_index_list())), "beta0")),
          elt_multiply(subtract(1, kappa),
            rvalue(beta0,
              cons_list(index_omni(),
                cons_list(index_uni(2), nil_index_list())), "beta0"))),
        "assigning variable beta");
      current_statement__ = 30;
      if (logical_eq(MCMC, 1)) {
        current_statement__ = 29;
        assign(chi, nil_index_list(),
          elt_divide(
            subtract(
              subtract(V,
                to_vector(normal_rng(0, rep_vector(tau, N), base_rng__))),
              alpha), beta), "assigning variable chi");
      } else {
        current_statement__ = 28;
        assign(chi, nil_index_list(), elt_divide(subtract(V, alpha), beta),
          "assigning variable chi");
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(kappa[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(chi[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(alpha[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(beta[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<double, -1, -1> alpha_raw;
      alpha_raw = Eigen::Matrix<double, -1, -1>(N, 2);
      stan::math::fill(alpha_raw, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> alpha_raw_flat__;
        current_statement__ = 1;
        assign(alpha_raw_flat__, nil_index_list(),
          context__.vals_r("alpha_raw"),
          "assigning variable alpha_raw_flat__");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 1;
            assign(alpha_raw,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              alpha_raw_flat__[(pos__ - 1)], "assigning variable alpha_raw");
            current_statement__ = 1;
            pos__ = (pos__ + 1);}}
      }
      Eigen::Matrix<double, -1, -1> beta_raw;
      beta_raw = Eigen::Matrix<double, -1, -1>(N, 2);
      stan::math::fill(beta_raw, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> beta_raw_flat__;
        current_statement__ = 2;
        assign(beta_raw_flat__, nil_index_list(),
          context__.vals_r("beta_raw"), "assigning variable beta_raw_flat__");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 2;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 2;
            assign(beta_raw,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              beta_raw_flat__[(pos__ - 1)], "assigning variable beta_raw");
            current_statement__ = 2;
            pos__ = (pos__ + 1);}}
      }
      Eigen::Matrix<double, -1, 1> theta_lr;
      theta_lr = Eigen::Matrix<double, -1, 1>(2);
      stan::math::fill(theta_lr, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> theta_lr_flat__;
        current_statement__ = 3;
        assign(theta_lr_flat__, nil_index_list(),
          context__.vals_r("theta_lr"), "assigning variable theta_lr_flat__");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 3;
          assign(theta_lr, cons_list(index_uni(sym1__), nil_index_list()),
            theta_lr_flat__[(pos__ - 1)], "assigning variable theta_lr");
          current_statement__ = 3;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> theta_lr_free__;
      theta_lr_free__ = Eigen::Matrix<double, -1, 1>(2);
      stan::math::fill(theta_lr_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      assign(theta_lr_free__, nil_index_list(),
        stan::math::ordered_free(theta_lr),
        "assigning variable theta_lr_free__");
      std::vector<double> theta_raw;
      theta_raw = std::vector<double>(J, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 4;
      assign(theta_raw, nil_index_list(), context__.vals_r("theta_raw"),
        "assigning variable theta_raw");
      double tau;
      tau = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      tau = context__.vals_r("tau")[(1 - 1)];
      double tau_free__;
      tau_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      tau_free__ = stan::math::lb_free(tau, 0);
      Eigen::Matrix<double, -1, 1> lambda;
      lambda = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(lambda, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> lambda_flat__;
        current_statement__ = 6;
        assign(lambda_flat__, nil_index_list(), context__.vals_r("lambda"),
          "assigning variable lambda_flat__");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 6;
          assign(lambda, cons_list(index_uni(sym1__), nil_index_list()),
            lambda_flat__[(pos__ - 1)], "assigning variable lambda");
          current_statement__ = 6;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> lambda_free__;
      lambda_free__ = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(lambda_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 6;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 6;
        assign(lambda_free__, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lub_free(lambda[(sym1__ - 1)], 0, 1),
          "assigning variable lambda_free__");}
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          vars__.emplace_back(
            rvalue(alpha_raw,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "alpha_raw"));
        }}
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          vars__.emplace_back(
            rvalue(beta_raw,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "beta_raw"));
        }}
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        vars__.emplace_back(theta_lr_free__[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        vars__.emplace_back(theta_raw[(sym1__ - 1)]);}
      vars__.emplace_back(tau_free__);
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(lambda_free__[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("alpha_raw");
    names__.emplace_back("beta_raw");
    names__.emplace_back("theta_lr");
    names__.emplace_back("theta_raw");
    names__.emplace_back("tau");
    names__.emplace_back("lambda");
    names__.emplace_back("theta");
    names__.emplace_back("alpha0");
    names__.emplace_back("beta0");
    names__.emplace_back("log_lik");
    names__.emplace_back("kappa");
    names__.emplace_back("chi");
    names__.emplace_back("alpha");
    names__.emplace_back("beta");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N),
                                             static_cast<size_t>(2)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N),
                                             static_cast<size_t>(2)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(2)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(J)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(J)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N),
                                             static_cast<size_t>(2)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N),
                                             static_cast<size_t>(2)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N_obs)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "alpha_raw" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "beta_raw" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "theta_lr" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "theta_raw" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "tau");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "lambda" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "alpha0" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "beta0" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "kappa" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "chi" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "alpha" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "alpha_raw" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "beta_raw" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "theta_lr" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "theta_raw" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "tau");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "lambda" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "alpha0" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "beta0" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "kappa" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "chi" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "alpha" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"alpha_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << 2 << "},\"block\":\"parameters\"},{\"name\":\"beta_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << 2 << "},\"block\":\"parameters\"},{\"name\":\"theta_lr\",\"type\":{\"name\":\"vector\",\"length\":" << 2 << "},\"block\":\"parameters\"},{\"name\":\"theta_raw\",\"type\":{\"name\":\"array\",\"length\":" << J << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"array\",\"length\":" << J << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"alpha0\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << 2 << "},\"block\":\"transformed_parameters\"},{\"name\":\"beta0\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << 2 << "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" << N_obs << "},\"block\":\"transformed_parameters\"},{\"name\":\"kappa\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"chi\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"alpha_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << 2 << "},\"block\":\"parameters\"},{\"name\":\"beta_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << 2 << "},\"block\":\"parameters\"},{\"name\":\"theta_lr\",\"type\":{\"name\":\"vector\",\"length\":" << 2 << "},\"block\":\"parameters\"},{\"name\":\"theta_raw\",\"type\":{\"name\":\"array\",\"length\":" << J << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"array\",\"length\":" << J << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"alpha0\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << 2 << "},\"block\":\"transformed_parameters\"},{\"name\":\"beta0\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << 2 << "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" << N_obs << "},\"block\":\"transformed_parameters\"},{\"name\":\"kappa\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"chi\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_FBAM_MINI_namespace::model_FBAM_MINI;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_FBAM_MINI_namespace::profiles__;
}
#endif
#endif
